stages:
  prepare_data:
    cmd: python ./prepare_data.py
    deps:
      - ./prepare_data.py
      - ./data/data.csv
    params:
      - data
    outs:
      - ./data/train.csv
      - ./data/test.csv
  train:
    cmd: python ./train.py
    deps:
      - ./train.py
      - ./data/train.csv
      - ./data/test.csv
    params:
     - train
    outs:
     - ./models/model.joblib
  evaluate:
    cmd: python ./evaluate.py
    deps:
      - ./evaluate.py
      - ./data/test.csv
      - ./models/model.joblib
    params:
      - evaluate
    outs:
      - ./results.yaml